[tool.poetry]
name = "lemvi-risk-management-platform"
version = "0.1.0"
description = "Google Cloud tools for gathering data from various sources"
authors = ["Christophe <christophe.alexandre@lemvi.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
